name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      $JENKINS_URL: "${{ secrets.JENKINS_URL }}"
      $JENKINS_USER: "${{ secrets.JENKINS_USER }}"
      $JENKINS_API_TOKEN: "${{ secrets.JENKINS_API_TOKEN }}"
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build/Pacakge with Maven
      run: |
          mvn -B package --file pom.xml
          mkdir staging
          cp target/*.war staging
    - name: Test with Maven
      run: mvn -B test --file pom.xml
    
    - name: Upload build artifacts to Azure blob storage
      uses: fixpoint/azblob-upload-artifact@v4    
      if: success()
      with:
        connection-string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        name: my-artifact
        path: staging 
        
    - name: Trigger Jenkins Deployment Job
      if: success()
      run: |
        #curl -X POST "$JENKINS_URL/job/java-maven/build" --user "$JENKINS_USER:$JENKINS_API_TOKEN"        
        curl -X POST "http://52.168.127.156:8080/job/java-maven/build" --user admin:117eb5c83c98ca6690b9eb33c6d9aa2192
